import type { Metadata } from "next";
import { cabinet, neima } from "@/lib/fonts";
import CustomCursor from "@/components/layout/CustomCursor";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinet.variable} ${neima.variable} font-cabinet antialiased`}
      >
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
